import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { cn } from '@/lib/utils';

import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Botifarma',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang='es'>
      <body className={cn('antialiased bg-[#E9EEF8]', montserrat.variable)}>
        <div className='size-full max-w-[90dvw] 2xl:max-w-[1447px] mx-auto'>
          {children}
        </div>
      </body>
    </html>
  );
}
