import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import { PageWidthContainer } from '@/components/layout/containers';
import { Footer } from '@/components/layout/footer';
import { Header } from '@/components/layout/header';
import { cn } from '@/lib/utils';

import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Botifarma',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang='es'>
      <body className={cn('antialiased', montserrat.variable)}>
        <section className='grid grid-rows-[auto_1fr_auto] gap-2 min-h-dvh'>
          <Header />

          <PageWidthContainer className='overflow-auto size-full'>
            {children}
          </PageWidthContainer>

          <Footer />
        </section>
      </body>
    </html>
  );
}
