import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Botifarma",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}
